apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/omprakash0210/flask-app.git
    targetRevision: HEAD
    path: web/flask_v1
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: flask-app
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
