apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: null
  labels:
    app: flask-app
    app.kubernetes.io/instance: flask-app
  name: flask-deploy
  namespace: argocd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - image: 'omprakash4pt/flask-app:v1'
          imagePullPolicy: Always
          name: flask-app
          ports:
            - containerPort: 5001
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 64Mi
          volumeMounts:
            - mountPath: /secrets/
              name: secret-volume
            - mountPath: /configs/
              name: config-volume
