apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  labels:
    app: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: flask-app:v1
        ports:
        - containerPort: 5001
---
apiVersion: apps/v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/instance: flask-app
  name: flask-pod
  namespace: argocd
spec:
  containers:
    - image: 'omprakash4pt/flask-app:v1'
      name: flask-app
      ports:
        - containerPort: 5001
